CREATE TABLE IF NOT EXISTS parent (
  id INT AUTO_INCREMENT PRIMARY KEY,
  label VARCHAR(255) NOT NULL,
  href VARCHAR(255) DEFAULT NULL,
  icon VARCHAR(100) DEFAULT NULL,
  defaultOpened TINYINT(1) DEFAULT 0
);