CREATE TABLE IF NOT EXISTS child (
  id INT AUTO_INCREMENT PRIMARY KEY,
  parent_id INT NOT NULL,
  label VARCHAR(255) NOT NULL,
  href VARCHAR(255) DEFAULT NULL,
  FOREIGN KEY (parent_id) REFERENCES parent(id) ON DELETE CASCADE
);