CREATE TABLE IF NOT EXISTS ra_tasks (
  id INT AUTO_INCREMENT PRIMARY KEY,
  todo_id INT NOT NULL,
  label VARCHAR(255) NOT NULL,
  finished BOOLEAN NOT NULL DEFAULT FALSE,
  position INT NOT NULL DEFAULT 0,
  page_name VARCHAR(255) NOT NULL
);